<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.1.1</Version>
    <AssemblyTitle>Jellyfin.Plugin.Jellyfin2PopFeed</AssemblyTitle>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Web/Configuration.html" />
    <None Remove="Web/Configuration.js" />
    <EmbeddedResource Include="Web/Configuration.html" />
    <EmbeddedResource Include="Web/Configuration.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.5">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.11.5">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>